---
- hosts: localhost
  user: root
  connection: local
  gather_facts: true

  tasks:
  - gem: name=bundler state=present

  - name: Generate database configuration
    action: template src=config/database.yml.sample dest=config/database.yml

  - name: Bundle Install
    action: shell bundle install

  - name: Create the database
    action: shell bundle exec rake db:create

  - name: Migrate the database
    action: shell bundle exec rake db:migrate

  - name: Prepare the database
    action: shell bundle exec rake db:test:prepare

  - name: rake spec
    action: shell bundle exec rake spec
